openapi: 3.1.0
info:
  title: Proxy for Google Calendar API
  description: |
    A proxy to simplify interactions with Google Calendar API.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://calendar.gooproxy.example.com
security:
  - googleOAuth: []
components:
  securitySchemes:
    googleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://gooproxy.wellcare.workers.dev/auth2/v2/auth
          tokenUrl: https://gooproxy.wellcare.workers.dev/auth2/token
          scopes:
            https://www.googleapis.com/auth/calendar: Full access to Google Calendar  
paths:
  /calendar/v3/calendars/primary/events:
    post:
      operationId: calendar.events.insert
      tags: [Google Calendar]
      summary: Create a new event in Google Calendar
      description: |
        Creates a new event in the primary calendar and returns the event details.
    get: 
      operationId: calendar.events.list
      tags: [Google Calendar]
      summary: Retrieve a list of events from primary calendar
      description: |
        Retrieves a list of events from the primary calendar.

  /calendar/v3/calendars/primary/events/{eventId}:
    parameters:
      - in: path
        name: eventId
        required: true
        description: The ID of the event to retrieve or update.
        schema:
          type: string

    get:
      operationId: calendar.events.get
      tags: [Google Calendar]
      summary: Retrieve an event by ID from Google Calendar
      description: |
        Retrieves an event from Google Calendar using its unique event ID.

    patch:
      operationId: calendar.events.patch
      tags: [Google Calendar]
      summary: Update an event in Google Calendar by ID
      description: |
        Updates an event. This method supports patch semantics. 
        Note that each patch request consumes three quota units; prefer using a get followed by an update. 
        The field values you specify replace the existing values. Fields that you don't specify in the request remain unchanged. 
        Array fields, if specified, overwrite the existing arrays; this discards any previous array elements.
