openapi: 3.1.0
info:
  title: Proxy for Google Drive API
  description: >
    This is a Google Drive API proxy that contains tools for agent to read and update files, comments, and replies on Google Drive. 
    All request parameters, query parameters, and bodies will be passed through and forwarded to the Google Drive API directly, adhering strictly to the Google Drive API specification.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://drive.gooproxy.wellcare.workers.dev
security:
  - googleOAuth: []
components:
  securitySchemes:
    googleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://drive.gooproxy.wellcare.workers.dev/auth2/v2/auth
          tokenUrl: https://drive.gooproxy.wellcare.workers.dev/auth2/token
          scopes:
            https://www.googleapis.com/auth/drive: Full access to Google Drive
paths:
  /drive/v3/files:
    post:
      operationId: files_create
      tags: [File]
      summary: Create a new file in Google Drive
      description: |
        Creates a new file in Google Drive with the provided file metadata and returns the file object.

  /drive/v3/files/{fileId}:
    get:
      operationId: files_get
      tags: [File]
      summary: Get a file's metadata or content by ID
      description: |
        Retrieves a file's metadata or content by its unique file ID.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file to retrieve.
          schema:
            type: string

    delete:
      operationId: files_delete
      tags: [File]
      summary: Permanently delete a file
      description: |
        Permanently deletes a file owned by the user without moving it to the trash.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file to delete.
          schema:
            type: string
    patch:
      operationId: files_update
      tags: [File]
      summary: Update a file's metadata and/or content
      description: |
        Updates a file's metadata and/or content.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file to udpate.
          schema:
            type: string

  /drive/v3/files/{fileId}/copy:
    post:
      operationId: files_copy
      tags: [File]
      summary: Create a copy of a file
      description: |
        Creates a copy of a file and applies any requested updates with patch semantics.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file to copy.
          schema:
            type: string

  /drive/v3/files/{fileId}/comments:
    post:
      operationId: comments_create
      tags: [Comments]
      summary: Create a comment on a file
      description: |
        Creates a comment on a file. The fields parameter must be set.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file to create comments on.
          schema:
            type: string
    get:
      operationId: comments_list
      tags: [Comments]
      summary: List a file's comments
      description: |
        Lists all comments on a file. The fields parameter must be set.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file to retrieve comments.
          schema:
            type: string

  /drive/v3/files/{fileId}/comments/{commentId}:
    get:
      operationId: comments_get
      tags: [Comments]
      summary: Get a comment by ID
      description: |
        Retrieves a comment by its unique comment ID.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file that the comment belongs to.
          schema:
            type: string
        - in: path
          name: commentId
          required: true
          description: The ID of the comment to retrieve, delete, or update.
          schema:
            type: string

    delete:
      operationId: comments_delete
      tags: [Comments]
      summary: Delete a comment
      description: |
        Deletes a comment on a file.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file that the comment belongs to.
          schema:
            type: string
        - in: path
          name: commentId
          required: true
          description: The ID of the comment to retrieve, delete, or update.
          schema:
            type: string

    patch:
      operationId: comments_update
      tags: [Comments]
      summary: Update a comment
      description: |
        Updates a comment with patch semantics.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file that the comment belongs to.
          schema:
            type: string
        - in: path
          name: commentId
          required: true
          description: The ID of the comment to retrieve, delete, or update.
          schema:
            type: string

  /drive/v3/files/{fileId}/comments/{commentId}/replies:
    post:
      operationId: replies_create
      tags: [Replies]
      summary: Create a reply to a comment
      description: |
        Creates a reply to a comment on a file.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file to create replies on.
          schema:
            type: string
        - in: path
          name: commentId
          required: true
          description: The ID of the comment to reply to.
          schema:
            type: string
    get:
      operationId: replies_list
      tags: [Replies]
      summary: List all replies to a comment
      description: |
        Lists all replies to a comment on a file.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file to retrieve replies for.
          schema:
            type: string
        - in: path
          name: commentId
          required: true
          description: The ID of the comment to retrieve replies for.
          schema:
            type: string

  /drive/v3/files/{fileId}/comments/{commentId}/replies/{replyId}:
    get:
      operationId: replies_get
      tags: [Replies]
      summary: Get a reply by ID
      description: |
        Retrieves a reply to a comment by its unique reply ID.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file that the reply belongs to.
          schema:
            type: string
        - in: path
          name: commentId
          required: true
          description: The ID of the comment that the reply belongs to.
          schema:
            type: string
        - in: path
          name: replyId
          required: true
          description: The ID of the reply to retrieve, delete, or update.
          schema:
            type: string

    delete:
      operationId: replies_delete
      tags: [Replies]
      summary: Delete a reply
      description: |
        Deletes a reply to a comment on a file.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file that the reply belongs to.
          schema:
            type: string
        - in: path
          name: commentId
          required: true
          description: The ID of the comment that the reply belongs to.
          schema:
            type: string
        - in: path
          name: replyId
          required: true
          description: The ID of the reply to retrieve, delete, or update.
          schema:
            type: string

    patch:
      operationId: replies_update
      tags: [Replies]
      summary: Update a reply
      description: |
        Updates a reply to a comment with patch semantics.
      parameters:
        - in: path
          name: fileId
          required: true
          description: The ID of the file that the reply belongs to.
          schema:
            type: string
        - in: path
          name: commentId
          required: true
          description: The ID of the comment that the reply belongs to.
          schema:
            type: string
        - in: path
          name: replyId
          required: true
          description: The ID of the reply to retrieve, delete, or update.
          schema:
            type: string