openapi: 3.1.0
info:
  title: Proxy for Gmail API
  description: |
    A proxy to simplify interactions with Gmail API.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://gmail.gooproxy.example.com
security:
  - googleOAuth: []
components:
  securitySchemes:
    googleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://gooproxy.wellcare.workers.dev/auth2/v2/auth
          tokenUrl: https://gooproxy.wellcare.workers.dev/auth2/token
          scopes:
            https://www.googleapis.com/auth/drive: Full access to Google Drive
            https://www.googleapis.com/auth/gmail.readonly: Read-only access to Gmail
            https://www.googleapis.com/auth/gmail.send: Send email from Gmail
            https://www.googleapis.com/auth/calendar: Full access to Google Calendar  
paths:
  /gmail/v1/users/{userId}/messages/{id}:
    parameters:
      - in: path
        name: userId
        required: true
        description: The email address of the user. Use "me" to indicate the authenticated user.
        schema:
          type: string
      - in: path
        name: id
        required: true
        description: The ID of the message to retrieve.
        schema:
          type: string

    get:
      operationId: gmail.users.messages.get
      tags: [Gmail]
      summary: Get the specified message
      description: |
        Retrieves the specified message from the user's mailbox.

  /gmail/v1/users/{userId}/messages:
    parameters:
      - in: path
        name: userId
        required: true
        description: The email address of the user. Use "me" to indicate the authenticated user.
        schema:
          type: string

    get:
      operationId: gmail.users.messages.list
      tags: [Gmail]
      summary: List the messages in the user's mailbox
      description: |
        Lists the messages in the user's mailbox, with options for pagination.

  /gmail/v1/users/{userId}/messages/send:
    parameters:
      - in: path
        name: userId
        required: true
        description: The email address of the user. Use "me" to indicate the authenticated user.
        schema:
          type: string

    post:
      operationId: gmail.users.messages.send
      tags: [Gmail]
      summary: Send the specified message
      description: |
        Sends the specified message to the recipients in the To, Cc, and Bcc headers.

  /gmail/v1/users/{userId}/drafts:
    parameters:
      - in: path
        name: userId
        required: true
        description: The email address of the user. Use "me" to indicate the authenticated user.
        schema:
          type: string

    post:
      operationId: gmail.users.drafts.create
      tags: [Gmail]
      summary: Create a new draft
      description: |
        Creates a new draft with the DRAFT label. You can specify the email content and recipients.

  /gmail/v1/users/{userId}/drafts/{id}:
    parameters:
      - in: path
        name: userId
        required: true
        description: The email address of the user. Use "me" to indicate the authenticated user.
        schema:
          type: string
      - in: path
        name: id
        required: true
        description: The ID of the draft to retrieve, update, or delete.
        schema:
          type: string

    get:
      operationId: gmail.users.drafts.get
      tags: [Gmail]
      summary: Get the specified draft
      description: |
        Retrieves the specified draft from the user's mailbox.

    delete:
      operationId: gmail.users.drafts.delete
      tags: [Gmail]
      summary: Delete a draft
      description: |
        Immediately and permanently deletes the specified draft.

    put:
      operationId: gmail.users.drafts.update
      tags: [Gmail]
      summary: Replace a draft's content
      description: |
        Replaces the content of an existing draft.

  /gmail/v1/users/{userId}/drafts/send:
    parameters:
      - in: path
        name: userId
        required: true
        description: The email address of the user. Use "me" to indicate the authenticated user.
        schema:
          type: string

    post:
      operationId: gmail.users.drafts.send
      tags: [Gmail]
      summary: Send the specified draft
      description: |
        Sends the specified, existing draft to the recipients in the To, Cc, and Bcc headers.

  /gmail/v1/users/{userId}/settings/vacation:
    parameters:
      - in: path
        name: userId
        required: true
        description: The email address of the user. Use "me" to indicate the authenticated user.
        schema:
          type: string

    get:
      operationId: gmail.users.settings.getVacation
      tags: [Gmail]
      summary: Get vacation responder settings
      description: |
        Retrieves the current vacation responder settings for the user.

    put:
      operationId: gmail.users.settings.updateVacation
      tags: [Gmail]
      summary: Update vacation responder settings
      description: |
        Updates the vacation responder settings, including the on/off status, subject, and message body.
