openapi: 3.1.0
info:
  title: Proxy for Google Docs API
  description: >
    This is a Google Docs API proxy that contains tools for agent to retrieve and apply batch updates to Google Docs documents. 
    All request parameters, query parameters, and bodies will be passed through and forwarded to the Google Docs API directly, adhering strictly to the Google Docs API specification.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://127.0.0.1:8787
security:
  - googleOAuth: []
components:
  securitySchemes:
    googleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://127.0.0.1:8787/auth2/v2/auth
          tokenUrl: http://127.0.0.1:8787/auth2/token
          scopes:
            https://www.googleapis.com/auth/drive: Full access to Google Drive
  schemas: {}
paths:
  /v1/documents/{documentId}/structure:
    get:
      operationId: documents_structure
      summary: Inspect the structure of a Google Docs document.
      description: |
        Inspect the document’s structure before applying any updates or changes.
        The response includes both the document's content, styles and other metadata, which can be large. 
      parameters:
        - in: path
          name: documentId
          required: true
          description: The ID of the document to retrieve. If user provide document link, please extract the documentId from it.
          schema:
            type: string
          example: 1s0gTYKvaqW7VHoSQg53Mu43KmA4im0mPGEoReAsmbO4
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
        
  /v1/documents/{documentId}/batchUpdate:
    post:
      operationId: documents_batchUpdate
      summary: Apply multiple updates to a Google Docs document
      description: |
        Applies multiple updates to a Google Docs document in a single action. 
        If user provide document link, please extract the documentId from it.
        For markdown format, you must convert to Google Docs format first.
      parameters:
        - in: path
          name: documentId
          required: true
          description: The ID of the document to apply the batch updates to.
          schema:
            type: string
            example: 1Q9pDyZsea-7wQAtJGD2XUu-skcDrg3Xz4Sev0atnGVw
      requestBody:
        description: |
          The request body should contain a list of update requests in the Google Docs API batch update format.
          Valid requests will be applied sequentially. If any update is invalid, the entire batch fails.
        content:
          application/json:
            schema:
              type: object
              properties:                 
                requests:
                  type: array
                  items:
                    type: object
                    description: A single update request, such as inserting text or formatting. Follow strictly Google Docs API specs.
                    properties: {}
              required: 
                - requests
              example:
                requests:
                  - insertText:
                      text: Hello, world!
                      location:
                        index: 1
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object

  /v1/documents/{documentId}/markdown/insert:
    post:
      tags:
        - Document
      operationId: documents_markdown_insert
      summary: Insert a markdown content to Google Docs
      description: |
        Insert a markdown content to Google Docs. 
        If user provide document link, please extract the documentId from it.
        The request body should contain a markdown content in base64 encoding.
      parameters:
        - in: path
          name: documentId
          required: true
          description: The ID of the document to apply the batch updates to.
          schema:
            type: string
          example: 1Q9pDyZsea-7wQAtJGD2XUu-skcDrg3Xz4Sev0atnGVw
      requestBody:
        description: The request body must contain the base64 encoded markdown content.
        content:
          application/json:
            schema:
              type: object
              properties:
                markdown:
                  type: string
                  description: The markdown content to insert, must be base64-encoded to avoid special characters issues.
                  example: IyBIZWxsbywgd29ybGQh
              required: [markdown]
              
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object

  /v1/documents/{documentId}/deleteContentRangeRequest:
    post:
      operationId: documents_deleteContentRangeRequest
      summary: Deletes content from the Google Docs document
      description: |
        Clear the content of a Google Docs document in the specified range.
        It will clear all content if range is not provided.
      parameters:
        - in: path
          name: documentId
          required: true
          description: The ID of the document to clear content. If user provide document link, please extract the documentId from it.
          schema:
            type: string  
      requestBody:
        description: The request body should contain the range to clear.
        content:
          application/json:
            schema:
              type: object
              properties:
                range:
                  type: object
                  description: Specifies a contiguous range of text, follow Range specification in Google Docs API.
                  properties:
                    startIndex:
                      type: integer
                      description: The start index of the range to clear, default to 1.
                      minimum: 1
                      default: 1
                    endIndex:
                      type: integer
                      description: The end index of the range to clear, default to the end of the document.
                      example: 100
                    segmentId:
                      type: string
                      description: The ID of the header, footer, or footnote that this range is contained in. An empty segment ID signifies the document's body.
                    tabId:
                      type: string
                      description: The tab that contains this range. When omitted, the request applies to the first tab.
              required: [range]
              example:
                range: { startIndex: 1, endIndex: 100 }
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
