openapi: 3.1.0
info:
  title: Proxy for Google Sheets API
  description: |
    A proxy to simplify interactions with Google Sheets API.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://sheets.gooproxy.wellcare.workers.dev
security:
  - googleOAuth: []
components:
  securitySchemes:
    googleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://sheets.gooproxy.wellcare.workers.dev/auth2/v2/auth
          tokenUrl: https://sheets.gooproxy.wellcare.workers.dev/auth2/token
          scopes:
            https://www.googleapis.com/auth/drive: Full access to Google Drive  
paths:
  /sheets/v4/spreadsheets:
    post:
      operationId: spreadsheets_create
      summary: Create a new spreadsheet
      description: |
        Creates a new blank spreadsheet with the specified title and returns the created spreadsheet.

  /sheets/v4/spreadsheets/{spreadsheetId}:
    parameters:
      - in: path
        name: spreadsheetId
        required: true
        description: The ID of the spreadsheet to retrieve or update.
        schema:
          type: string

    get:
      operationId: spreadsheets_get
      summary: Retrieve a spreadsheet by ID
      description: |
        By default, data within grids is not returned. 
        You can include grid data by specifying a field mask listing your desired fields using the fields URL parameter.
        For large spreadsheets, as a best practice, retrieve only the specific spreadsheet fields that you want. 
        To retrieve only subsets of spreadsheet data, use the ranges URL parameter.

  /sheets/v4/spreadsheets/{spreadsheetId}/batchUpdate:
    parameters:
      - in: path
        name: spreadsheetId
        required: true
        description: The ID of the spreadsheet to batch update.
        schema:
          type: string

    post:
      operationId: spreadsheets_batch_update
      summary: Batch update a spreadsheet
      description: |
        Applies a list of updates to the document in a single request.
        Multiple changes can be made in a batch update.
        Each request is validated before being applied. 
        If any request is not valid, then the entire request will fail and nothing will be applied.

  /sheets/v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}/copyTo:
    parameters:
      - in: path
        name: spreadsheetId
        required: true
        description: The ID of the spreadsheet containing the sheet to copy.
        schema:
          type: string
      - in: path
        name: sheetId
        required: true
        description: The ID of the sheet to copy.
        schema:
          type: string

    post:
      operationId: spreadsheets_sheets_copy_to
      summary: Copy a sheet to a new spreadsheet
      description: |
        Copies a single sheet from a spreadsheet to another spreadsheet. Returns the properties of the newly created sheet.

  /sheets/v4/spreadsheets/{spreadsheetId}/values/batchClear:
    parameters:
      - in: path
        name: spreadsheetId
        required: true
        description: The ID of the spreadsheet to clear values from.
        schema:
          type: string

    post:
      operationId: spreadsheets_values_batch_clear
      summary: Clears one or more ranges of values from a spreadsheet.
      description: |
        Clears one or more ranges of values from a spreadsheet. 
        Only values are cleared -- all other properties of the cell (such as formatting and data validation) are kept.

  /sheets/v4/spreadsheets/{spreadsheetId}/values/batchGet:
    parameters:
      - in: path
        name: spreadsheetId
        required: true
        description: The ID of the spreadsheet to retrieve values from.
        schema:
          type: string

    post:
      operationId: spreadsheets_values_batch_get
      summary: Returns one or more ranges of values from a spreadsheet.
      description: |
        Returns one or more ranges of values from a spreadsheet. Each range can be specified using A1 notation.

  /sheets/v4/spreadsheets/{spreadsheetId}/values/batchUpdate:
    parameters:
      - in: path
        name: spreadsheetId
        required: true
        description: The ID of the spreadsheet to update values in.
        schema:
          type: string

    post:
      operationId: spreadsheets_values_batch_update
      summary: Sets values in one or more ranges of a spreadsheet.
      description: |
        You can modify or overwrite cell values for specific ranges. 
        Must specify a valueInputOption, and one or more ValueRanges.
